name: edit_yaml

on: 
  push

jobs:

  edit_yaml_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v3
      with: 
        python-version: '3.10'

  
    - name: Get Config
      id: get_conf
      run: python ./read.py

    - name: editing yaml
      run: |
        env="dev"
        echo "environment=$env" >> $GITHUB_ENV
        echo $env
        if [ $env == "dev" ]
        then 
          appName=${{ steps.get_conf.outputs.appName }}"-"${{ github.ref_name }}"-"${{ steps.get_conf.outputs.version }}
          echo $appName
          path="/api/"${{ steps.get_conf.outputs.appName }}"/"${{ steps.get_conf.outputs.version }}
          echo $path
          fileName="./values2.yaml"
          echo $fileName
        else
          appName=${{ steps.get_conf.outputs.appName }}"-"${{ github.ref_name }}"-"${{ steps.get_conf.outputs.version }}"-ci"
          path="/ci/api/"${{ steps.get_conf.outputs.appName }}"/"${{ steps.get_conf.outputs.version }}
          fileName="./values2.yaml"
        fi
        path="${path//\//\\/}"
        echo $path
        sed -i "s/appName: .*/appName: $appName/1" $fileName
        sed -i "s/path: .*/path: $path/1" $fileName
        sed -i "s/value: .*/value $path/2g" $fileName
