name: edit_yaml

on: 
  workflow_dispatch

jobs:

  steps_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v3
      with: 
        python-version: '3.10'

  
    - name: Get Config
      id: get_conf
      run: python ./read.py

    - name: editing yaml
      run: |
        env="dev"
        echo "environment=$env" >> $GITHUB_ENV
        echo $env
        if [ $env == "dev" ]
        then 
          appName=${{ steps.get_conf.outputs.appName }}"-"$GITHUB_REF"-"${{ steps.get_conf.outputs.version }}
          echo $appName
          path="\/api"$appName"\/"${{ steps.get_conf.outputs.version }}
          echo $path
          fileName="./values2.yaml"
          echo $fileName
        else
          appName=${{ steps.get_conf.outputs.appName }}"-"$GITHUB_REF"-"${{ steps.get_conf.outputs.version }}"-ci"
          path="\/ci\/api\/"$appName"\/"${{ steps.get_conf.outputs.version }}
          fileName="./values3.yaml"
        fi
        sed -i "s/appName:.*/appName: $appname/1" $fileName
        sed -i "s/path: .*/path: $path/1" $fileName
        sed -i "s/value: .*/value $path/2g" $fileName
