name: editYaml

on: 
  workflow_dispatch

jobs:

  steps_testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - run: |
        echo "appName=fraud-transaction-mgmt" >> $GITHUB_ENV
        echo "path=abcd\/efgh\/gvhj" >> $GITHUB_ENV
        echo "${{ env.appName }}"
        echo "${{ env.path }}"

