name: steps_test

on: push

jobs:
  steps_testing:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Create Env Variable
        run: |
          cat > temp.txt
          ls --help > temp.txt
          export varii=$(echo "helloooooooooooo")
          arr=()
          while IFS= read -r line; do
            arr+=("$line")
          done <temp.txt
          echo "${arr[*]}"
          echo "${arr[0]}"

      -
        name: Display Variable
        run: |
          echo $varii

