name: steps_test

on: push

jobs:
  steps_testing:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Create Env Variable
        run: |
          cat > temp.txt
          echo "Hellooo World uhgeai oihgifzshergtoirjhoirj  rgnjdzgni;rohigtuighrnkbjrdnez;gioreiojirrnn()ujfilzerngkr \n seiufwe" > temp.txt
          export varii=$(echo "helloooooooooooo")
          readarray -t Arr < temp.txt
          echo "${Arr[0]}"
          echo "${Arr[1]}"
          echo $varii
          cat temp.txt

      -
        name: Display Variable
        run: |
          echo $varii

