name: steps_test

on: push

jobs:
  steps_testing:
    runs-on: ubuntu-latest
    env:
      Check: None
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Create Env Variable
        run: |
          cat > temp.txt
          ls --help > temp.txt
          IFS=$'\n' read -d '' -r -a lines < temp.txt
          export varii=$(echo "${lines[-1]}")

      -
        name: Display Variable
        run: |
          echo $varii

