name: steps_test

on: push

jobs:
  steps_testing:
    runs-on: ubuntu-latest
    env:
      newbie: hi
    steps:

      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Create Env Variable
        run: |
            cat > temp.txt
            ls --help > temp.txt
            arr=()
            while IFS= read -r line; do
              arr+=("$line")
            done <temp.txt
            export vari="${arr[0]}"
            echo "$vari"
            echo "${vari:3:1}"
            echo "${arr[-1]}"
            echo "newbie=${vari:3:1}" >> $GITHUB_ENV
            rm temp.txt
      -
        name: Display Variable
        run: |
          echo ${{ env.newbie }}
          if [[ "${{ env.newbie }}" == "g" ]]; then
            echo "Successful"
          else
            echo "Failed"
            exit 1
          fi

      - name: This step should skipped
        run: |
          echo "Hi, This step should be skipped"
