name: steps_test

on: push

jobs:
  steps_testing:
    runs-on: ubuntu-latest
    env:
      Check: None
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Create Env Variable
        run: |
          cat > temp.txt
          echo "Hello"
      -
        name: Display Variable
        run: |
          echo $varii

