name: steps_test

on: push

jobs:
  steps_testing:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Create Env Variable
        run: |
          export varii=$(echo "helloooooooooooo")

      -
        name: Display Variable
        run: |
          echo $varii

