name: read_file

on: push

jobs:

  steps_testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v4
      with: 
        python-version: '3.10'
    
    - name: Get config 
      id: getty
      run: python ./read.py

    - run: echo "${{ steps.getty.outputs.foo }}"