name: read_file

on: workflow_dispatch

jobs:

  steps_testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v4
      with: 
        python-version: '3.10'
    
    - run: python ./test/read.py