name: read_file

on: 
  workflow_dispatch:
    tags:
      - '*'



jobs:

  steps_testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v4
      with: 
        python-version: '3.10'
    
    - name: Get config 
      id: getty
      run: python ./read.py 

    - run: |
        echo "${{ steps.getty.outputs.foo }}"
        result=$(curl ${{ steps.getty.outputs.url }} | tail -1)
        echo $result
        echo "${{ github.ref }}"
        echo "${{ github.ref_name }}"
        echo "${{ github.action_ref }}"

    - name: Writing in yaml 
      id: write_yaml
      uses: python ./write.py 