name: read_properties

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Define env name'     
        required: true
        default: 'prod'
      branch:
        description: 'Define branch name'     
        required: true
        default: 'master'

jobs:
  steps_testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1 

    # test 1
    - name: Using input values
      run: |
        echo "Env: ${{ github.event.inputs.environment }}" 
        echo "Branch: ${{ github.event.inputs.branch }}"